export const ACTION_TYPE = {
  SET_RATINGS_FILTER: "SET_RATINGS_FILTER",
  SORT_PRICE: "SORT_PRICE",
  SET_CATEGORIES_FILTER: "SET_CATEGORIES_FILTER",
  SET_OTHER_FILTERS: "SET_OTHER_FILTERS",
  CLEAR__FILTERS: "CLEAR__FILTERS",
};
